//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.25 at 11:18:02 PM MSK 
//


package gmail.alexejkrawez.medicine;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{Medicine}string"/>
 *         &lt;element name="pharm" type="{Medicine}string"/>
 *         &lt;element name="group" type="{Medicine}string"/>
 *         &lt;element name="analogs" type="{Medicine}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="versions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="version" type="{Medicine}string"/>
 *                   &lt;element name="certificate" type="{Medicine}string"/>
 *                   &lt;element name="package" type="{Medicine}string"/>
 *                   &lt;element name="dosage" type="{Medicine}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "pharm",
    "group",
    "analogs",
    "versions"
})
@XmlRootElement(name = "medicine")
public class Medicine {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String pharm;
    @XmlElement(required = true)
    protected String group;
    @XmlElement(required = true)
    protected List<String> analogs;
    @XmlElement(required = true)
    protected Medicine.Versions versions;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the pharm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPharm() {
        return pharm;
    }

    /**
     * Sets the value of the pharm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPharm(String value) {
        this.pharm = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the analogs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the analogs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnalogs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAnalogs() {
        if (analogs == null) {
            analogs = new ArrayList<String>();
        }
        return this.analogs;
    }

    public void setAnalogs(List<String> analogs) {
        this.analogs = analogs;
    }

    /**
     * Gets the value of the versions property.
     * 
     * @return
     *     possible object is
     *     {@link Medicine.Versions }
     *     
     */
    public Medicine.Versions getVersions() {
        return versions;
    }

    /**
     * Sets the value of the versions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Medicine.Versions }
     *     
     */
    public void setVersions(Medicine.Versions value) {
        this.versions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="version" type="{Medicine}string"/>
     *         &lt;element name="certificate" type="{Medicine}string"/>
     *         &lt;element name="package" type="{Medicine}string"/>
     *         &lt;element name="dosage" type="{Medicine}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version",
        "certificate",
        "_package",
        "dosage"
    })
    public static class Versions {

        @XmlElement(required = true)
        protected String version;
        @XmlElement(required = true)
        protected String certificate;
        @XmlElement(name = "package", required = true)
        protected String _package;
        @XmlElement(required = true)
        protected String dosage;

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the certificate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCertificate() {
            return certificate;
        }

        /**
         * Sets the value of the certificate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCertificate(String value) {
            this.certificate = value;
        }

        /**
         * Gets the value of the package property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPackage() {
            return _package;
        }

        /**
         * Sets the value of the package property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPackage(String value) {
            this._package = value;
        }

        /**
         * Gets the value of the dosage property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDosage() {
            return dosage;
        }

        /**
         * Sets the value of the dosage property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDosage(String value) {
            this.dosage = value;
        }

        @Override
        public String toString() {
            return "Versions{\n" +
                    "version = '" + version + "\'\n" +
                    "certificate = '" + certificate + "\'\n" +
                    "package = '" + _package + "\'\n" +
                    "dosage = '" + dosage + "\'" +
                    '}';
        }
    }

    @Override
    public String toString() {
        return "Medicine{\n" +
                "name = '" + name + "\'\n" +
                "pharm = '" + pharm + "\'\n" +
                "group = '" + group + "\'\n" +
                "analogs = " + analogs + "\n" +
                versions +
                '}';
    }
}
